#!/bin/bash -e

for i in /sys/devices/system/cpu/cpu[0-9]*/cpufreq/scaling_governor; do echo "ondemand" > $i; done

sum() {
  SUM=$(md5sum $1 | cut -f1 -d' ')
  if [ $? != 0 ]; then
    echo -1
  else
    echo $SUM
  fi
}

bootfs_override() {
  local p=$1

  if [[ -e "/boot/horizon-cfg${p}" ]]; then
    if ! [[ -e "${p}" ]]; then
      mkdir -p $(dirname $p)
    else

      if [[ "$(sum "/boot/horizon-cfg${p}")" == "$(sum "${p}")" ]]; then
        return
      fi

      mv "${p}" "${p}.overridden"
    fi

    systemd-cat -t horizon-configure echo -e "/boot/horizon-cfg${p} exists, copying to ${p}"
    cp -v /boot/horizon-cfg"${p}" "${p}"
  fi
}

bootfs_override "/etc/default/horizon-env"
bootfs_override "/etc/horizon/anax.json"
bootfs_override "/usr/horizon/bin/horizon-env-preprocess"
