#!/bin/bash -e

for i in /sys/devices/system/cpu/cpu[0-9]*/cpufreq/scaling_governor; do echo "ondemand" > $i; done

mkdir -p /opt/hzn_common

if [ -d /boot/horizon/config ]; then
  cp -af /boot/horizon/config /opt/hzn_common/
fi

# stuff from /var may overwrite the boot stuff
if [ -d /var/horizon/config ]; then
  cp -af /var/horizon/config /opt/hzn_common/
fi

